app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    fullname = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy="dynamic")
    comments = db.relationship('Comment',backref =  'user',lazy = "dynamic")
    
    @property
    def password(self):

        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
        
    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    pitch_title = db.Column(db.String)
    pitch_category = db.Column(db.String)
    pitch_comment = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    comments = db.relationship('Comment',backref =  'pitch',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,category):
        pitches = Pitch.query.filter_by(pitch_category=category).all()
        return pitches

    @classmethod
    def getPitchId(cls,id):
        pitch = Pitch.query.filter_by(id=id).first()
        return pitch

class Comment(db.Model):
    __tablename__ = 'comments'
 
    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(500))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def saveComment(self):
        db.session.add(self)
        db.session.commit()
        

    @classmethod
    def getComments(cls,pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField,SelectField
from wtforms.validators import Required,Email,EqualTo
from wtforms import ValidationError
from ..models import User

class updateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself',validators = [Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    pitch_title = StringField('Pitch title',validators=[Required()])
    pitch_category = SelectField('Pitch Category', choices = [('Select category','Select category'),('interview', 'Interview'), ('product', 'Product'),('promotion','Promotion'),('pickup','Pickup Lines')], validators=[Required()])
    pitch_comment = TextAreaField('Your Pitch')
    submit = SubmitField('Submit Pitch')

class CommentForm(FlaskForm):
    text = TextAreaField('Write a comment:',validators=[Required()])
    submit = SubmitField('Submit')        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE


from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
 
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Pitch,Comment
from .forms import updateProfile,PitchForm,CommentForm
from .. import db,photos
from flask_login import login_required,current_user

@main.route('/')
def index():

    return render_template('index.html')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    pitches = Pitch.query.filter_by(user_id = user.id).all()
    if user is None:
        abort(404)

    return render_template('profile/profile.html',user = user,pitches=pitches)   

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = updateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()
           
        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)  

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/pitch/newpitch',methods= ['POST','GET'])
@login_required
def newPitch():
    pitch = PitchForm()
    if pitch.validate_on_submit():
        title = pitch.pitch_title.data
        category = pitch.pitch_category.data;
        yourPitch = pitch.pitch_comment.data

        #update pitch instance

        newPitch = Pitch(pitch_title = title,pitch_category = category,pitch_comment = yourPitch,user= current_user)

        #save pitch
        newPitch.save_pitch()
        return redirect(url_for('.index'))

    title = 'NEW PITCH'
    return render_template('newPitch.html',title = title,pitchform = pitch)  

@main.route('/category/interview',methods= ['GET'])
def displayInterviewCategory():
    interviewPitches = Pitch.get_pitches('interview')
    return render_template('category/interview.html',interviewPitches = interviewPitches)
    
@main.route('/category/product',methods= ['POST','GET'])
def displayProductCategory():
    productPitches = Pitch.get_pitches('product')
    return render_template('category/product.html',productPitches = productPitches)

@main.route('/category/promotion',methods= ['POST','GET'])
def displayPromotionCategory():
    promotionPitches = Pitch.get_pitches('promotion')
    return render_template('category/promotion.html',promotionPitches = promotionPitches)

@main.route('/category/pickup',methods= ['POST','GET'])
def displayPickupCategory():
    pickupPitches = Pitch.get_pitches('pickup')
    return render_template('category/pickup.html',pickupPitches = pickupPitches)

@main.route('/comment/<int:id>',methods= ['POST','GET'])
@login_required
def viewPitch(id):
    onepitch = Pitch.getPitchId(id)
    comments = Comment.getComments(id)

    if request.args.get("like"):
        onepitch.likes = onepitch.likes + 1

        db.session.add(onepitch)
        db.session.commit()

        return redirect("/comment/{pitch_id}".format(pitch_id=pitch.id))

    elif request.args.get("dislike"):
        onepitch.dislikes = onepitch.dislikes + 1

        db.session.add(onepitch)
        db.session.commit()

        return redirect("/comment/{pitch_id}".format(pitch_id=pitch.id))

    commentForm = CommentForm()
    if commentForm.validate_on_submit():
        comment = commentForm.text.data

        newComment = Comment(comment = comment,user = current_user,pitch_id= id)

        newComment.saveComment()

    return render_template('comment.html',commentForm = commentForm,comments = comments,pitch = onepitch)

    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block styles%}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">

{%endblock%}

{%block scripts%}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

{%endblock%}

app/templates/category/interview.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="">

    <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
          <h2 class="card-title h1-responsive font-bold">Interview Pitches</h2>
        </div>
      </div>
    <hr>
    <div class="row">
        {{macro.displayPitches(interviewPitches)}}
    </div>
</div>
{%endblock%}

app/templates/category/pickup.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
      <h2 class="card-title h1-responsive font-bold">Pickup Pitches</h2>
    </div>
  </div>
    <hr>
    <div class="row">
        {{macro.displayPitches(pickupPitches)}}
    </div>
</div>
{%endblock%}

app/templates/category/product.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
      <h2 class="card-title h1-responsive font-bold">Production Pitches</h2>
    </div>
  </div>
    <hr>
    <div class="row">
        {{macro.displayPitches(productPitches)}}
    </div>
</div>
{%endblock%}

app/templates/category/promotion.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
      <h2 class="card-title h1-responsive font-bold">Promotion Pitches</h2>
    </div>
  </div>
    <hr>
    <div class="row">
        {{macro.displayPitches(promotionPitches)}}
    </div>
</div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}
{% block content %}
<div>
    <div class="container">
        <div class="row">
        <div class="col-sm"> 
            <h3 class="pt-3">Your Pitch</h3>
            <hr>
            <p>Title : {{pitch.pitch_title}}</p>
            <p>Description : {{pitch.pitch_comment}}</p>
            <p>Date Posted : {{pitch.posted}}</p>

            <a href="/comment/{{pitch.id}}?like=1">
                <i class="far fa-thumbs-up"></i>
            </a>{{pitch.likes}} <a href="/comment/{{pitch.id}}?dislike=1">
                <i class="far fa-thumbs-down"></i>
            </a>{{pitch.dislikes}}
        </div>
        <div class="col-sm">
            <h3 class="pt-3">Comments</h3>
            <hr>
        
            {% if current_user.is_authenticated %}
            {{ wtf.quick_form(commentForm) }}
            {%endif%}
            <h3>Display comments</h3>
            {{macro.displayComments(comments)}}
        
        </div>
        <div class="col-md-2"></div>
        </div>
        </div>

</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block content %}
<div class="">
  <div class="jumbotron jumbotron-fluid" style="background-color: beige;">
    <div class="container text-white text-center">
      <h2 class="card-title h1-responsive font-bold" style="color: black;">Welcome to Pitches Places</h2>
      <a class="btn btn-outline btn-md" href=" {{url_for('main.newPitch')}}" ><i class="fas fa-clone left" style="color: brown;" ></i><p class="davy" style="color: blue;">CREATE A PITCH</p></a>
    </div>
  </div>

<h3 class="text-center text-uppercase text-bold">Categories</h3>
<hr>

  <div class="row m-3">
    <div class="col-sm">
      <div class=" card col-sm pt-2">
        <div class="well well-lg p-3" style="text-align: center;">
            <h3 class="">Interviews Pitches</h3>
            <hr>
            <p>You're just trying to go out there and give seven innings. Seven innings, 105 pitches, that's a good outing. </p>
                <a href="{{url_for('main.displayInterviewCategory')}}" class="btn btn-default btn-center -center">
                View Pitch</a>
        </div>
    </div>
    </div>
    <div class="col-sm">
      <div class=" card col-sm mt-2">
        <div class="well well-lg p-3" style="text-align: center;">
            <h3>Promotion Pitches</h3>
            <hr>
            <p>You're just trying to go out there and give seven innings. Seven innings, 105 pitches, that's a good outing. </p>
                <a href="{{url_for('main.displayPromotionCategory')}}" class="btn btn-default btn-center -center">
                View Pitch</a>
        </div>
    </div>
    </div>
  </div>

  <div class="row m-3">
    <div class="col-sm">
      <div class=" card col-sm mt-2">
        <div class="well well-lg p-3" style="text-align: center;">
            <h3>Product Pitches</h3>
            <hr>
            <p>A summary of what should be included in a product pitch </p>
                <a href="{{url_for('main.displayProductCategory')}}" class="btn btn-default btn-center -center">
                View Pitch</a>
        </div>
      </div>
      
    </div>
    <div class="col-sm">
      <div class=" card col-sm mt-2">
        <div class="well well-lg p-3" style="text-align: center;">
            <h3>Pickup Lines Pitches</h3>
            <hr>
            <p>In this country, since footballs made from pigs' bladders were whacked into goals without nets, we've played on full-size pitches. Whatever our age.</p>
                <a href="{{url_for('main.displayPickupCategory')}}" class="btn btn-default btn-center -center">
                View Pitch</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Footer -->
<footer class="page-footer font-small blue-grey darken-3">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/">pitch</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</div>

{% endblock %}

app/templates/macros.html
{% macro displayPitches(pitches_list)%}
{%for pitch in pitches_list%}   
    <div class="row">
        <div class="col-sm m-5">
            <div class=" card col-sm mt-2">
              <div class="well well-lg p-3" style="text-align: center;">
                  <h3>{{pitch.pitch_title}}</h3>
                  <hr>
                  <p>{{pitch.pitch_comment|truncate(50)}}</p>
                  <p>By : {{pitch.user.username}} </p>
                  <p>Posted on: {{pitch.posted}}</p>
                      <a href="/comment/{{pitch.id}}" class="btn btn-default btn-center -center">
                      Comment</a>
              </div>
          </div>
          </div>
    </div>
{%endfor%}
{%endmacro%}

{%macro displayComments(comments_list)%}
    {%for comment in comments_list%}
        <div class="col-md-12">
            <p>{{comment.comment}}</p>
            <h5>By : {{comment.user.username}}</h5>
        </div>
    {%endfor%}
{%endmacro%}

app/templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark elegant-color">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="/">Pitch
        <span class="sr-only">(current)</span>
    </a>
  
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="basicExampleNav">
  
      <ul class="navbar-nav ml-auto">
        {% if current_user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" href = "/">{{current_user.username}}</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a>
            <a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a>
            {% else %}
            <a class="dropdown-item text-white" href="{{url_for('auth.login')}}">Login</a>
            {%endif%}
          </div>
        </li>
      </ul>
    </div>
  
  </nav>

app/templates/newPitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
    <h3 class="mt-3 pb-3 text-center">Create Pitch</h3>
    <hr>
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8 card mt-3 p-5">

{{wtf.quick_form(pitchform)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
  <h3 class="text-center mt-3">My Profile</h3>
<hr>
<div class="row">
<!-- displaying  Username-->
  <div class="col-4">


    {% if user.profile_pic_path %}

  <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

  {%else%}
  <p>No profile picture</p>

  {% endif %}

</div>

<div class="col-8">
 <!--Displaying user bio-->
  <div class="mr-5">
    <span class="row">
      <h3 class="h3"> Username : </h3><p class="h3">{{user.username| capitalize}} </p>
    </span>
    {% if user.bio %}
    <p class="h3"> Bio : {{user.bio}}</p>
  {%else%}
    <p> {{user.username| capitalize}} has no bio </p>
  {% endif %}

  </div>
  {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data" class="pt-5">
    <div class="form-group">
      <input type="file"  name="photo" class="form-control" required>
    </div>
    <div class="form-group">
      <!-- <input type="submit" class="form-control"> -->
      <button class="btn btn-info" type="submit">Submit</button>
    </div>
  </form>
    {% endif %}

    {% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}" class="btn btn-default btn-center -center">
  Edit Profile</a>
{% endif %}

</div>
</div>

  <h3 class="text-uppercase text-center"> My Pitches</h3>
  <hr>
 {{macro.displayPitches(pitches)}}
</div>
{% endblock %}
  </div>

  

  

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}